services:
#    gis.example:
#        class: Geocuba\GISBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.gis.twig.extension.globals:
        class: Geocuba\GISBundle\Twig\RegisterGlobalsExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
